spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=doanbinh2208@gmail.com
spring.mail.password=jtydmgnmubiimrrp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=doanbinh2208@gmail.com
